# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Session-AttributeBased
version:      0.07
version_from: lib/POE/Session/AttributeBased.pm
installdirs:  site
requires:
    POE:                           0
    POE::Session:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
